server:
  port: 3344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiangjiahui/springcloud-config.git
          search-paths:
            - springcloud-config  #搜索目录
          default-label: master   #读取分支
          username: 2464674651@qq.com
          password: XJH9901042832
          skip-ssl-validation: true
#rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

#rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"


eureka:
  instance:
    instance-id: cloud-config-server-3344
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka