server:
  port: 80

spring:
  application:
    name: cloud-consumer-service

eureka:
  instance:
    instance-id: cloud-consumer-order-80
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka