server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud1?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: root
  profiles:
    active: dev
  zipkin: #添加zipkin监控链路的支持
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1  #采样率值介于0到1之间,1表示全部采集


eureka:
  instance:
    instance-id: cloud-provider-payment-8001
    prefer-ip-address: true
  #    lease-expiration-duration-in-seconds: 2  Eureka服务端在收到最后一次心跳后等待时间上限,单位默认为90秒,超时将剔除该微服务
  #    lease-renewal-interval-in-seconds: 1   Eureka客户端向服务端发送心跳的时间,单位默认为30秒
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

mybatis-plus:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.xjh.springcloud.**.domain
  global-config:
    db-config:
      logic-delete-field: 0
      logic-not-delete-value: 1