server:
  port: 9527

spring:
  application:
    name: cloud-provider-gateway-9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_route   #路由的ID,没有固定规则但要求唯一,建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/user/getAllUser   #断言,路径相匹配的进行路由

        - id: payment_route2   #路由的ID,没有固定规则但要求唯一,建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/user/getUser/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    instance-id: cloud-provider-gateway
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
