server:
  port: 8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud1?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: root
  profiles:
    active: dev


eureka:
  instance:
    instance-id: cloud-provider-payment-8002
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

mybatis-plus:
  mapper-locations: classpath:mybatis/**/*.xml
  type-aliases-package: com.xjh.springcloud.**.domain
  global-config:
    db-config:
      logic-delete-field: 0
      logic-not-delete-value: 1