server:
  port: 8007

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  instance:
    instance-id: cloud-provider-hystrix-payment-8007
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#日志文件配置
logging:
  config: classpath:logback-spring.xml
