server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com   #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己,eureka服务端本身就是注册中心
    fetch-registry: false   #false表示自己端就是注册中心,我的职责是维护服务实例,并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  server:
#    关闭自我保护机制,使不可用的微服务被即使剔除
#    enable-self-preservation: false
##    设置检测微服务不可用的时间
#    eviction-interval-timer-in-ms: 2000
